import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Kyle Park
 *
 */
public final class RSSReader {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSReader() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title</title>
     * </head> <body>
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <table border="1">
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */

    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel") : ""
                + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        //Top of HTML file

        out.println("<html>");
        out.println("<head>");
        out.println("<title>");

        //Go to getChildElement

        int position = getChildElement(channel, "title");

        String title = "";

        //See if there is title or not

        if (channel.child(position).numberOfChildren() == 0) {
            out.println("No Title.");
        } else {
            title = channel.child(position).child(0).label();
            out.println(title);
        }

        out.println("</title>");
        out.println("</head>");
        out.println("<body>");

        position = getChildElement(channel, "link");

        //Link format in HTML

        out.print("<h1><a href=\"");

        out.print(channel.child(position).child(0).label());
        out.print("\">");
        out.print(title);

        out.println("</a></h1>");

        position = getChildElement(channel, "description");

        //Description: Check if empty, or print

        out.println("<p>");

        if (channel.child(position).numberOfChildren() == 0) {
            out.println("No description.");
        } else {
            out.println(channel.child(position).child(0).label());
        }

        out.println("</p>");

        //Table

        out.println("<table border = \"1\">");
        out.println("<tr>");
        out.println("<th>Date</th>");
        out.println("<th>Source</th>");
        out.println("<th>News</th>");
        out.println("</tr>");

    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table>
     * </body> </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */

    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("</table>");
        out.println("</body>");
        out.println("</html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */

    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        //For loop to find first occurence of tag, returns -1 if nothing

        int nothing = -1;

        for (int i = 0; i < xml.numberOfChildren(); i++) {
            if (xml.child(i).isTag()) {
                if (xml.child(i).label().equals(tag)) {
                    nothing = i;
                }
            }
        }
        return nothing;
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */

    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item") : ""
                + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        int title = getChildElement(item, "title");
        int link = getChildElement(item, "link");
        int description = getChildElement(item, "description");
        int pubDate = getChildElement(item, "pubDate");
        int source = getChildElement(item, "source");

        out.println("<tr>");

        if (pubDate != -1) {
            out.println(
                    "<td>" + item.child(pubDate).child(0).label() + "</td>");
        } else {
            out.println("<td>No date available</td>");
        }

        if (source != -1) {
            out.println("<td>");
            out.print("<a href=\"");
            out.print(item.child(source).attributeValue("url"));
            out.println("\">" + item.child(source).child(0).label() + "</a>");
            out.println("</td>");
        } else {
            out.println("<td>No source available</td>");
        }

        out.println("<td>");

        if (link != -1) {
            out.print("<a href=\"");
            out.print(item.child(link).child(0).label());
            out.print("\">");
        }
        if (title != -1) {
            if (item.child(title).child(0).label().equals("")) {
                out.print("No title available");
            } else {
                out.print(item.child(title).child(0).label());
            }
        } else if (description != -1) {
            if (item.child(description).child(0).label().equals("")) {
                out.print("No description available");
            } else {
                out.print(item.child(description).child(0).label());
            }
        }
        if (link != -1) {
            out.println("</a>");
        }
        out.println("</td>");
        out.println("</tr>");

    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */

    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        out.print("Enter the URL of an RSS 2.0 feed: ");
        String website = in.nextLine();
        XMLTree xml = new XMLTree1(website);

        if (xml.attributeValue("version").equals("2.0")
                && xml.label().equals("rss") && xml.hasAttribute("version")) {

            out.print(
                    "Enter the name of the output file with .html at the end: ");

            String fileName = in.nextLine();
            SimpleWriter fileOut = new SimpleWriter1L(fileName);

            XMLTree channel = xml.child(0);

            outputHeader(channel, fileOut);

            for (int i = 0; i < channel.numberOfChildren(); i++) {
                if (channel.child(i).isTag()) {
                    if (channel.child(i).label().equals("item")) {
                        XMLTree item = channel.child(i);
                        processItem(item, fileOut);
                    }
                }
            }
            outputFooter(fileOut);
            fileOut.close();
        } else {
            out.println("The URL inputted is not a valid RSS 2.0 file.");
        }
        out.println();
        in.close();
        out.close();

    }

}